---
- hosts: "{{ hosts }}"
  tasks:
    - pause:
        prompt:
                Warning! DEV Deployment!!
                Please enter the secret phrase
      when: '"dev" in hosts'
      register: input_password
      no_log: true

    - fail:
        msg: "Invalid password"
      when: (not input_password|skipped and input_password.changed == false) and (input_password.user_input != lookup('file', '/home/sudha/git_repositories/passphrase/.passfile'))

    - debug: msg="The password is valid. Proceeding with DEV deployments........"
      when: (not input_password|skipped and input_password.changed == false) and (input_password.user_input == lookup('file', '/home/sudha/git_repositories/passphrase/.passfile'))

    - name: The current working direcotry
      shell: /bin/pwd
      register: pwd_output

    - name: what got saved
      debug: var=pwd_output

    - name: printing return code
      debug: msg="The return code of my command is {{ pwd_output['rc'] }}"

    - name: the output is
      debug: msg="the output is {{ pwd_output['stdout']}}"

